### ISSUE TITLE
Berkshelf install --except option not working

### ISSUE THREAD

**Issue by suharshan** [berkshelf/solve#52]
I'm using berkshelf version 3.2.4. I have created a group as follows in my Berkshelf file.

`group :mfs do`
`  cookbook 'git'`
`end`

Then I issue the following command to install my dependencies.
`berks install --except mfs`

This command is supposed to download every other cookbook except git. But it downloads git as well.

**Comment by reset** [comment]
@suharshan this an issue for the Berkshelf repository, not Solve. Would you re-open the ticket there please with the complete contents of your Berksfile and metadata.rb of any cookbooks referenced by the Berksfile? Thanks!
