### ISSUE TITLE
Solve or Berkshelf issue

### ISSUE THREAD

**Issue by acondrat** [berkshelf/solve#57]
Problem is being reproduced in solve-2.0.3 only. 

> $ git clone https://github.com/acondrat/solveissue
> $ cd solveissue
> $ bundle
> $ bundle exec berks
> Resolving cookbook dependencies...
> Fetching 'solveissue' from source at .
> Fetching cookbook index from https://supermarket.chef.io...
> /home/acondrat/.rvm/gems/ruby-2.1.8/gems/solve-2.0.3/lib/solve/ruby_solver.rb:144:in `block in sort_dependencies': undefined method `payload' for nil:NilClass (NoMethodError)
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/solve-2.0.3/lib/solve/ruby_solver.rb:141:in `each'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/solve-2.0.3/lib/solve/ruby_solver.rb:141:in `sort_by'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/solve-2.0.3/lib/solve/ruby_solver.rb:141:in `sort_dependencies'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:431:in `push_state_for_requirements'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:423:in `require_nested_dependencies_for'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:411:in `activate_spec'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:353:in `attempt_to_swap_possibility'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:333:in `attempt_to_activate_existing_spec'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:318:in `attempt_to_activate'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:147:in `process_topmost_state'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolution.rb:72:in `resolve'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/molinillo-0.4.4/lib/molinillo/resolver.rb:42:in `resolve'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/solve-2.0.3/lib/solve/ruby_solver.rb:195:in `resolve_with_error_wrapping'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/solve-2.0.3/lib/solve/ruby_solver.rb:75:in `resolve'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/solve-2.0.3/lib/solve.rb:64:in `it!'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/lib/berkshelf/resolver.rb:78:in `resolve'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/lib/berkshelf/installer.rb:175:in `install_from_universe'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/lib/berkshelf/installer.rb:39:in `run'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/lib/berkshelf/berksfile.rb:421:in `install'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/lib/berkshelf/cli.rb:143:in `install'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/lib/berkshelf/cli.rb:52:in `dispatch'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/lib/berkshelf/cli.rb:27:in `execute!'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/gems/berkshelf-4.3.1/bin/berks:5:in `<top (required)>'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/bin/berks:23:in `load'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/bin/berks:23:in `<main>'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `eval'
> 	from /home/acondrat/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in `<main>'

Works fine with solve-2.0.2.

**Comment by scopenco** [comment]
Seems this problem affect to last chefdk 0.12.0  https://github.com/chef/chef-dk/issues/771

**Comment by tjsingleton** [comment]
I found that specifying the transitive dependency version in the berksfile in another workaround.

**Comment by reset** [comment]
@danielsdeleo gonna ping you on this one since you did the legwork on the alternate solver backend

**Comment by danielsdeleo** [comment]
I was able to make a failing test case here: https://github.com/berkshelf/solve/tree/chefdk-771 (https://github.com/berkshelf/solve/commit/b84500e80c22e0596b530838f7a7d299f6f9f870)

Aside from that I don't have any leads as to what is going on, yet. I added some debugging to Molinillo itself and it definitely "looks weird" but I don't know Molinillo deeply enough to know what to make of it.

**Comment by danielsdeleo** [comment]
I fixed the upstream bug and that fix has since been released. cf. https://github.com/CocoaPods/Molinillo/issues/38
