### ISSUE TITLE
Solver returns NoSolutionError with a constraint that does not exist

### ISSUE THREAD

**Issue by maxvt** [berkshelf/solve#62]
Hi all, I'm having a Berkshelf issue that so far has been traced into the solver. This is with Berkshelf 4.3.5 but with Solve bumped to 3.0.1 and molinillo at 0.5.1.

This is a rather complex graph but the problem is simple. `nginx-2.2.0` introduces a requirement for `build-essential (~> 1.4)`. Another required package, `homebrew-1.10.0`, does not have any dependencies but the resolution fails with `build-essential (>= 2.1.2) required by homebrew-1.10.0`. I have ascertained, by prying into the artifacts of the graph just before Solve.it! is called, that the artifact with name homebrew and version 1.10.0 does not have any dependencies. Homebrew does introduce a dependency to build-essential in a later version.

Any suggestions on how to investigate this further?

**Comment by maxvt** [comment]
Homebrew-relevant lines from the solver log:
```
Creating possibility state for homebrew (>= 0.0.0) (29 remaining)
Attempting to activate homebrew-2.1.2
Activated homebrew at homebrew-2.1.2
Requiring nested dependencies (build-essential (>= 2.1.2))
Creating possibility state for homebrew (= 1.10.0) (1 remaining)
Attempting to activate homebrew-1.10.0
Found existing spec (homebrew-2.1.2)
Activated homebrew at homebrew-1.10.0
Requiring nested dependencies ()
Creating possibility state for homebrew (>= 0.0.0) (29 remaining)
Attempting to activate homebrew-2.1.2
Found existing spec (homebrew-1.10.0)
Creating possibility state for build-essential (>= 2.1.2) (24 remaining)
```

**Comment by nmattam** [comment]
I ran into the same issue today with Berkshelf 4.3.5 and Solve 2.0.3. However, I was able to fix it when I locked Solve to 2.0.2.

**Comment by thommay** [comment]
First of all - my apologies that this has been open so long. Solve and molinilo have been pretty extensively changed since this bug was raised; are you still seeing this?

**Comment by maxvt** [comment]
We abandoned our attempts to fix Molinillo and require the gecode solver in our Berksfile, which fixed our problem.

`solver :gecode, :required`

**Comment by nmattam** [comment]
I'm currently using Berkshelf 6.3.1 and solve 4.0.0 and not seeing this issue.
